project:
  type: book
  output-dir: docs

book:
  title: "Statistics Notes"
  author: "Josh Errickson"
  page-navigation: false
  chapters:
    - index.qmd
    - divideby4.qmd
    - iccirr.qmd
    - logitinterpretation.qmd
    - logtransform.qmd
    - mixedModelsSPSS.qmd
    - moderationMediation.qmd
    - modifying_stata_builtin.qmd
    - poissonapprox.qmd
    - randomselection.qmd
    - responsesurfaceplot.qmd
    - splinesvsinteraction.qmd
    - svy_gsem_teffects.qmd
    - visualizeCollinearity.qmd
    - vizrandomeffects.qmd
    - xtsetvsmixed.qmd

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    number-sections: false
