project:
  type: website
  output-dir: docs

website:
  title: "Statistics Notes"
  navbar:
    left:
      - text: R Topics
        menu:
          - responsesurfaceplot.qmd
      - text: Stata Topics
        menu:
          - svy_gsem_teffects.qmd
          - logitinterpretation.qmd
          - xtsetvsmixed.qmd
          - modifying_stata_builtin.qmd
      - text: Statistical Topics
        menu:
          - splinesvsinteraction.qmd
          - randomselection.qmd
          - iccirr.qmd
          - divideby4.qmd
          - vizrandomeffects.qmd
          - mixedModelsSPSS.qmd
          - moderationMediation.qmd
          - visualizeCollinearity.qmd
          - logtransform.qmd
      - href: index.html
        text: Back to list

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    toc: true
