---
title: "Interpreting Mixed Model coefficients versus GEE model coefficients"
---

When there is a "random effect" to account for (e.g. repeated measures), two
options for fitting are mixed models (aka hierarchical models) or generalized
estimating equations (GEE).

The mixed model is often described as the conditional model whereas the GEE is
often described as the marginal model.

Let's consider the following model:

$$
  mpg \sim \beta_0 + \beta_1weight
$$

Say this data is collected experimentally; we take a collection of cars with a
measured weight, drive them $X$ miles and say they use $Y$ gallons of gas, their
mileage per gallon is $X/Y$. To address variability between cars, we use several
of each type, e.g. 5 Ford Escapes, 3 Chevrolet Cruzes, etc.

Let's interpret the coefficient $\beta_1$ associated with weight (weight
measured in pounds).

In the mixed model: Two cars, of the same model, will differ by $\beta_1$ if
their weight differs by 1 pound.

In the GEE: $\beta_1$ is the change in mpg when we see a 1 pound increase of
weight, averaged across all models.
